### ISSUE TITLE
maven-polyglot project should use polyglot maven

### ISSUE THREAD

**Issue by jkubrynski** [takari/maven-polyglot#20]
Maybe the project itself should take its own benefits and use poms written in groovy or yaml?

**Comment by jvanzyl** [comment]
Possibly but I don't actually mind XML :-) But on a practical level right now I can debug through the entire Maven stack in Eclipse and there are a couple hard codings of "pom.xml" in the M2Eclipse code base so that would break my debugging use case. We'll get there. The project may take off, but the primary target for this release is for the JRuby developers so they don't have to use a custom Maven distribution. But I totally agree that full IDE support will be necessary if Polyglot becomes popular.
